// import { Link } from "next/link";

import { useSession } from "next-auth/react";
import Head from "next/head";
import { Logo } from "~/components/svgs/logo";
import { ProfileDD } from "~/components/ui/ProfileDD";
import { IoIosNotificationsOutline as BellClose } from "react-icons/io";
import { ProfilePic } from "~/components/ui/profile-pic";
import Link from "next/link";
export default function Header() {
  const { data: sessionData } = useSession();
  if (!sessionData) {
    return null;
  }

  return (
    <>
      <Head>
        <title> Create an article</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <nav className="container flex w-full items-baseline justify-between     p-4">
        <div className="flex  items-center gap-3">
          <Link href="/" className="h-7  w-11 overflow-hidden rounded-full">
            <Logo />
            {/* search input */}
          </Link>
          <h1 className=" ">Draft by {sessionData?.user?.name}</h1>
          {/* saved or not  */}
          <span className="text-xs text-gray-500">Saved</span>
        </div>

        <div className="flex items-center gap-5 pt-1 text-lg">
          <button
            onClick={() => console.log("publish  TODO")}
            className="rounded-full  bg-green-600 px-3 py-1 text-white transition-all duration-200 hover:bg-gray-600 hover:text-white"
          >
            Publish
          </button>
          <BellClose className="h-7 w-7" />
          <ProfileDD
            user={sessionData?.user}
            before={
              <div className=" w-45 flex h-12 items-center justify-center gap-2 ">
                <ProfilePic author={sessionData?.user} className="h-12 w-12" />
                <Link href="/profile" className="flex flex-col">
                  <span className=" ">{sessionData?.user?.name}</span>
                  <span className="hover:underlin text-gray-600">
                    @{sessionData?.user?.name}
                  </span>
                </Link>
              </div>
            }
          />
        </div>
      </nav>
    </>
  );
}
